TASK: text-classification
DATASET_NAME: imdb
DATASET_CONFIG_NAME: null
EVAL_DATASET: test # default should be 'validation'
BASE_MODEL_NAME: distilbert-base-uncased
METRIC_NAMES:
  - name: "accuracy"
  - name: "f1"
    args: 
      average: "weighted"
BATCH_SIZE: 16
NUM_EPOCHS: 3
LEARNING_RATE: 0.00002
LOG_LEVEL: error
