TASK: text-classification
DATASET_NAME: glue
DATASET_CONFIG_NAME: cola
EVAL_DATASET: test # default should be 'validation'
BASE_MODEL_NAME: distilbert-base-uncased
METRICS:
  - accuracy: {}
  - f1      : {average: weighted}
  - glue    : ['cola']
BATCH_SIZE: 16
NUM_EPOCHS: 3
LEARNING_RATE: 0.00002
LOG_LEVEL: error
